(load "tests/precedence-list/precedence-list.lisp")
(load "tests/generic-functions/generic-functions.lisp")
(load "tests/auxiliary-methods/auxiliary-methods.lisp")
(format t "~%")
(format t "============== ASSIGNMENT EXAMPLES ====================~%")
(format t "~%")
(load "tests/auxiliary-methods/example.lisp")
(load "tests/multiple-dispatch/example.lisp")
(load "tests/multiple-inheritance/example.lisp")
(format t "~%")
(format t "============== ADDITIONAL REQUIREMENTS ====================~%")
(format t "~%")
(load "tests/additional-requirements/cache/cache.lisp")
(load "tests/additional-requirements/eql-specializer/eql-specializer.lisp")
(load "tests/additional-requirements/argument-precedence-order/argument-precedence-order.lisp")