(load "tests/precedence-list/precedence-list.lisp")
(load "tests/generic-functions/generic-functions.lisp")
(load "tests/multiple-dispatch/example.lisp")
(load "tests/multiple-inheritance/example.lisp")
(load "tests/auxiliary-methods/auxiliary-methods.lisp")
(load "tests/auxiliary-methods/example.lisp")