(in-package :closless)
(load "src/utils/tests.lisp")
(load "src/miniclos/loader.lisp")

(defclass Person () ())
(defclass Staff (Person) ())
(defclass Student (Person) ())
(defclass PhDStudent (Student Staff) ())

(defgeneric study (p))
(defmethod study ((p Person))
  (declare (ignore p))
  "I'm not a student.")
(defmethod study ((p Student))
  (declare (ignore p))
  "Let's study.")
(defmethod study ((p Staff))
  (declare (ignore p))
  (concatenate 'string "I work with students, but " (call-next-method)))

(defgeneric greet (p))
(defmethod greet ((p Person))
  (declare (ignore p))
  "How are you?")
(defmethod greet ((p Staff))
  (declare (ignore p))
  (concatenate 'string "Time is ticking. " (call-next-method)))
(defmethod greet ((p Student))
  (declare (ignore p))
  (concatenate 'string "Deadlines? Deadlines! " (call-next-method)))
(defmethod greet ((p PhDStudent))
  (declare (ignore p))
  (concatenate 'string "Let's research! " (call-next-method)))

(defvar phdstudent (make-instance 'PhDStudent))
(defvar person (make-instance 'Person))
(defvar staff (make-instance 'Staff))

(format t "Multiple Inheritance | Assignment example | Students => Start testing~%")
(format t "~%")

(assert-equals (print-command (study phdstudent)) "Let's study.")
(format t "~%")
(assert-equals (print-command (study person)) "I'm not a student.")
(format t "~%")
(assert-equals (print-command (study staff)) "I work with students, but I'm not a student.")
(format t "~%")
(assert-equals (print-command (greet phdstudent)) "Let's research! Deadlines? Deadlines! Time is ticking. How are you?")
(format t "~%")

(unbound-variables '(<Person> <Staff> <Student> <PhDStudent> study greet phdstudent person staff))

(format t "Multiple Inheritance | Assignment example | Students => All the tests passed~%")
(format t "~%")